# Boilerplate code generated by OVITO Pro 3.15.0
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
from ovito.vis import *
from ovito.qt_compat import QtCore
import glob
import os

def get_files_with_glob(directory_path, wildcard):
    # Construct the full search pattern (e.g., "./my_folder/*.txt")
    search_pattern = os.path.join(directory_path, wildcard)
    
    # glob.glob returns a list of matching string paths
    # Adding recursive=False (default). Change to True and use "**/*.txt" for subdirectories.
    file_list = glob.glob(search_pattern)
    
    # Optional: filter out directories that might match the wildcard
    file_list = [f for f in file_list if os.path.isfile(f)]
    
    return file_list


# ==== Set up pipeline ==== #

modA = SliceModifier()
modA.distance = -10.0
modA.normal = [1.0, 1.0, 0.0]
modA.inverse = True
modA.render_plane = True
modA.gridslice_vis.color_mapping_mode = SurfaceMeshVis.ColorMappingMode.Vertex
modB = SliceModifier()
modB.distance = 10.0
modB.normal = [1.0, -1.0, 0.0]
modB.render_plane = True
modB.gridslice_vis.color_mapping_mode = SurfaceMeshVis.ColorMappingMode.Vertex
# Data import:
my_directory = "./"
my_wildcard = "hopper_mur*_mus*_wallmur*_wallmus*.dump" 

matched_files = get_files_with_glob(my_directory, my_wildcard)
matched_files = ['hopper_mur0.1_mus0.3_wallmur0_wallmus0.dump', 'hopper_mur0.1_mus0.3_wallmur0.1_wallmus0.3.dump']
pipeline = import_file(matched_files[0], multiple_frames = True)
parts = matched_files[0].split("_")
mur = parts[1][3:]
mus = parts[2][3:]
wallmur = parts[3][7:]
wallmus = parts[4][7:][:-5]
name = "hopper_mur{}_mus{}_wallmur{}_wallmus{}".format(mur,mus,wallmur,wallmus)

# Color coding:
pipeline.modifiers.append(ColorCodingModifier(
    property = 'c_acontact', 
    end_value = 6.0, 
    gradient = ColorCodingModifier.Viridis()))


# Slice:
pipeline.modifiers.append(modA)
# Slice:
pipeline.modifiers.append(modB)

# ======= Set up visual elements ======= #

# Configure visual elements for pipeline 
pipeline.compute().cell.vis.line_width = 0.3
pipeline.compute().particles.vis.radius = 8e-05
pipeline.compute().particles.vis.scaling = 0.95
pipeline.compute().particles.vis.shape = ParticlesVis.Shape.Circle
# Add pipelines to visualization scene
pipeline.add_to_scene()

# ========== Set up rendering ========== #

# Viewport setup:
vp = Viewport(
    type = Viewport.Type.Top, 
    fov = 285.157028517, 
    camera_pos = [0.847880686834395, 260.325160397344, 0.0]
    )

#vp.render_anim(filename=name+'.mp4', size=(1024, 1024), fps=10.0, every_nth=1)
vp.render_image(filename=name+'last.png', size=(1024, 1024), frame=pipeline.num_frames-1)
# Rendering:
for dump in matched_files[1:]:
    pipeline.source.load(dump)
    parts = dump.split("_")
    mur = parts[1][3:]
    mus = parts[2][3:]
    wallmur = parts[3][7:]
    wallmus = parts[4][7:][:-5]
    name = "hopper_mur{}_mus{}_wallmur{}_wallmus{}".format(mur,mus,wallmur,wallmus)
    # Configure visual elements for pipeline 
    pipeline.compute().cell.vis.line_width = 0.3
    pipeline.compute().particles.vis.radius = 8e-05
    pipeline.compute().particles.vis.scaling = 0.95
    pipeline.compute().particles.vis.shape = ParticlesVis.Shape.Circle
    # Add pipelines to visualization scene
    pipeline.add_to_scene()


    
    #vp.render_anim(filename=name+'.mp4', size=(1024, 1024), fps=10.0, every_nth=1)
    vp.render_image(filename=name+'last.png', size=(1024, 1024), frame=pipeline.num_frames-1)
